# This Makefile is for the Text::Unidecode extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.30_01 (Revision: Revision: 4535 ) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:

#     NAME => q[Text::Unidecode]
#     VERSION_FROM => q[lib/Text/Unidecode.pm]
#     dist => { COMPRESS=>q[gzip -9f], SUFFIX=>q[gz] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/perl/5.8/Config.pm)

# They may have been overridden via Makefile.PL or on the command line
AR = ar
CC = cc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
LD = cc
LDDLFLAGS = -shared -L/usr/local/lib
LDFLAGS =  -L/usr/local/lib
LIBC = /lib/libc-2.6.1.so
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 2.6.15.7
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.8.8
SITEARCHEXP = /usr/local/lib/perl/5.8.8
SO = so
EXE_EXT = 
FULL_AR = /usr/bin/ar
VENDORARCHEXP = /usr/lib/perl5
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = Text::Unidecode
NAME_SYM = Text_Unidecode
VERSION = 0.04
VERSION_MACRO = VERSION
VERSION_SYM = 0_04
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 0.04
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = /usr
PERLPREFIX = $(PREFIX)
SITEPREFIX = $(PREFIX)/local
VENDORPREFIX = $(PREFIX)
INSTALLPRIVLIB = $(PERLPREFIX)/share/perl/5.8
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = $(SITEPREFIX)/share/perl/5.8.8
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = $(VENDORPREFIX)/share/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = $(PERLPREFIX)/lib/perl/5.8
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = $(SITEPREFIX)/lib/perl/5.8.8
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = $(VENDORPREFIX)/lib/perl5
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = $(PERLPREFIX)/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = $(SITEPREFIX)/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = $(VENDORPREFIX)/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = $(PERLPREFIX)/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = $(SITEPREFIX)/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = $(VENDORPREFIX)/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = $(PERLPREFIX)/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = $(SITEPREFIX)/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = $(VENDORPREFIX)/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = $(PERLPREFIX)/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = $(SITEPREFIX)/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = $(VENDORPREFIX)/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.8
PERL_ARCHLIB = /usr/lib/perl/5.8
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/perl/5.8/CORE
PERL = /usr/bin/perl
FULLPERL = /usr/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/share/perl/5.8/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.30_01
MM_REVISION = Revision: 4535 

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
FULLEXT = Text/Unidecode
BASEEXT = Unidecode
PARENT_NAME = Text
DLBASE = $(BASEEXT)
VERSION_FROM = lib/Text/Unidecode.pm
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = lib/Text/Unidecode.pm

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)/Text
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/Text

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/Text/Unidecode.pm \
	lib/Text/Unidecode/x00.pm \
	lib/Text/Unidecode/x01.pm \
	lib/Text/Unidecode/x02.pm \
	lib/Text/Unidecode/x03.pm \
	lib/Text/Unidecode/x04.pm \
	lib/Text/Unidecode/x05.pm \
	lib/Text/Unidecode/x06.pm \
	lib/Text/Unidecode/x07.pm \
	lib/Text/Unidecode/x09.pm \
	lib/Text/Unidecode/x0a.pm \
	lib/Text/Unidecode/x0b.pm \
	lib/Text/Unidecode/x0c.pm \
	lib/Text/Unidecode/x0d.pm \
	lib/Text/Unidecode/x0e.pm \
	lib/Text/Unidecode/x0f.pm \
	lib/Text/Unidecode/x10.pm \
	lib/Text/Unidecode/x11.pm \
	lib/Text/Unidecode/x12.pm \
	lib/Text/Unidecode/x13.pm \
	lib/Text/Unidecode/x14.pm \
	lib/Text/Unidecode/x15.pm \
	lib/Text/Unidecode/x16.pm \
	lib/Text/Unidecode/x17.pm \
	lib/Text/Unidecode/x18.pm \
	lib/Text/Unidecode/x1e.pm \
	lib/Text/Unidecode/x1f.pm \
	lib/Text/Unidecode/x20.pm \
	lib/Text/Unidecode/x21.pm \
	lib/Text/Unidecode/x22.pm \
	lib/Text/Unidecode/x23.pm \
	lib/Text/Unidecode/x24.pm \
	lib/Text/Unidecode/x25.pm \
	lib/Text/Unidecode/x26.pm \
	lib/Text/Unidecode/x27.pm \
	lib/Text/Unidecode/x28.pm \
	lib/Text/Unidecode/x2e.pm \
	lib/Text/Unidecode/x2f.pm \
	lib/Text/Unidecode/x30.pm \
	lib/Text/Unidecode/x31.pm \
	lib/Text/Unidecode/x32.pm \
	lib/Text/Unidecode/x33.pm \
	lib/Text/Unidecode/x4d.pm \
	lib/Text/Unidecode/x4e.pm \
	lib/Text/Unidecode/x4f.pm \
	lib/Text/Unidecode/x50.pm \
	lib/Text/Unidecode/x51.pm \
	lib/Text/Unidecode/x52.pm \
	lib/Text/Unidecode/x53.pm \
	lib/Text/Unidecode/x54.pm \
	lib/Text/Unidecode/x55.pm \
	lib/Text/Unidecode/x56.pm \
	lib/Text/Unidecode/x57.pm \
	lib/Text/Unidecode/x58.pm \
	lib/Text/Unidecode/x59.pm \
	lib/Text/Unidecode/x5a.pm \
	lib/Text/Unidecode/x5b.pm \
	lib/Text/Unidecode/x5c.pm \
	lib/Text/Unidecode/x5d.pm \
	lib/Text/Unidecode/x5e.pm \
	lib/Text/Unidecode/x5f.pm \
	lib/Text/Unidecode/x60.pm \
	lib/Text/Unidecode/x61.pm \
	lib/Text/Unidecode/x62.pm \
	lib/Text/Unidecode/x63.pm \
	lib/Text/Unidecode/x64.pm \
	lib/Text/Unidecode/x65.pm \
	lib/Text/Unidecode/x66.pm \
	lib/Text/Unidecode/x67.pm \
	lib/Text/Unidecode/x68.pm \
	lib/Text/Unidecode/x69.pm \
	lib/Text/Unidecode/x6a.pm \
	lib/Text/Unidecode/x6b.pm \
	lib/Text/Unidecode/x6c.pm \
	lib/Text/Unidecode/x6d.pm \
	lib/Text/Unidecode/x6e.pm \
	lib/Text/Unidecode/x6f.pm \
	lib/Text/Unidecode/x70.pm \
	lib/Text/Unidecode/x71.pm \
	lib/Text/Unidecode/x72.pm \
	lib/Text/Unidecode/x73.pm \
	lib/Text/Unidecode/x74.pm \
	lib/Text/Unidecode/x75.pm \
	lib/Text/Unidecode/x76.pm \
	lib/Text/Unidecode/x77.pm \
	lib/Text/Unidecode/x78.pm \
	lib/Text/Unidecode/x79.pm \
	lib/Text/Unidecode/x7a.pm \
	lib/Text/Unidecode/x7b.pm \
	lib/Text/Unidecode/x7c.pm \
	lib/Text/Unidecode/x7d.pm \
	lib/Text/Unidecode/x7e.pm \
	lib/Text/Unidecode/x7f.pm \
	lib/Text/Unidecode/x80.pm \
	lib/Text/Unidecode/x81.pm \
	lib/Text/Unidecode/x82.pm \
	lib/Text/Unidecode/x83.pm \
	lib/Text/Unidecode/x84.pm \
	lib/Text/Unidecode/x85.pm \
	lib/Text/Unidecode/x86.pm \
	lib/Text/Unidecode/x87.pm \
	lib/Text/Unidecode/x88.pm \
	lib/Text/Unidecode/x89.pm \
	lib/Text/Unidecode/x8a.pm \
	lib/Text/Unidecode/x8b.pm \
	lib/Text/Unidecode/x8c.pm \
	lib/Text/Unidecode/x8d.pm \
	lib/Text/Unidecode/x8e.pm \
	lib/Text/Unidecode/x8f.pm \
	lib/Text/Unidecode/x90.pm \
	lib/Text/Unidecode/x91.pm \
	lib/Text/Unidecode/x92.pm \
	lib/Text/Unidecode/x93.pm \
	lib/Text/Unidecode/x94.pm \
	lib/Text/Unidecode/x95.pm \
	lib/Text/Unidecode/x96.pm \
	lib/Text/Unidecode/x97.pm \
	lib/Text/Unidecode/x98.pm \
	lib/Text/Unidecode/x99.pm \
	lib/Text/Unidecode/x9a.pm \
	lib/Text/Unidecode/x9b.pm \
	lib/Text/Unidecode/x9c.pm \
	lib/Text/Unidecode/x9d.pm \
	lib/Text/Unidecode/x9e.pm \
	lib/Text/Unidecode/x9f.pm \
	lib/Text/Unidecode/xa0.pm \
	lib/Text/Unidecode/xa1.pm \
	lib/Text/Unidecode/xa2.pm \
	lib/Text/Unidecode/xa3.pm \
	lib/Text/Unidecode/xa4.pm \
	lib/Text/Unidecode/xac.pm \
	lib/Text/Unidecode/xad.pm \
	lib/Text/Unidecode/xae.pm \
	lib/Text/Unidecode/xaf.pm \
	lib/Text/Unidecode/xb0.pm \
	lib/Text/Unidecode/xb1.pm \
	lib/Text/Unidecode/xb2.pm \
	lib/Text/Unidecode/xb3.pm \
	lib/Text/Unidecode/xb4.pm \
	lib/Text/Unidecode/xb5.pm \
	lib/Text/Unidecode/xb6.pm \
	lib/Text/Unidecode/xb7.pm \
	lib/Text/Unidecode/xb8.pm \
	lib/Text/Unidecode/xb9.pm \
	lib/Text/Unidecode/xba.pm \
	lib/Text/Unidecode/xbb.pm \
	lib/Text/Unidecode/xbc.pm \
	lib/Text/Unidecode/xbd.pm \
	lib/Text/Unidecode/xbe.pm \
	lib/Text/Unidecode/xbf.pm \
	lib/Text/Unidecode/xc0.pm \
	lib/Text/Unidecode/xc1.pm \
	lib/Text/Unidecode/xc2.pm \
	lib/Text/Unidecode/xc3.pm \
	lib/Text/Unidecode/xc4.pm \
	lib/Text/Unidecode/xc5.pm \
	lib/Text/Unidecode/xc6.pm \
	lib/Text/Unidecode/xc7.pm \
	lib/Text/Unidecode/xc8.pm \
	lib/Text/Unidecode/xc9.pm \
	lib/Text/Unidecode/xca.pm \
	lib/Text/Unidecode/xcb.pm \
	lib/Text/Unidecode/xcc.pm \
	lib/Text/Unidecode/xcd.pm \
	lib/Text/Unidecode/xce.pm \
	lib/Text/Unidecode/xcf.pm \
	lib/Text/Unidecode/xd0.pm \
	lib/Text/Unidecode/xd1.pm \
	lib/Text/Unidecode/xd2.pm \
	lib/Text/Unidecode/xd3.pm \
	lib/Text/Unidecode/xd4.pm \
	lib/Text/Unidecode/xd5.pm \
	lib/Text/Unidecode/xd6.pm \
	lib/Text/Unidecode/xd7.pm \
	lib/Text/Unidecode/xf9.pm \
	lib/Text/Unidecode/xfa.pm \
	lib/Text/Unidecode/xfb.pm \
	lib/Text/Unidecode/xfc.pm \
	lib/Text/Unidecode/xfd.pm \
	lib/Text/Unidecode/xfe.pm \
	lib/Text/Unidecode/xff.pm

PM_TO_BLIB = lib/Text/Unidecode/x33.pm \
	blib/lib/Text/Unidecode/x33.pm \
	lib/Text/Unidecode/x6d.pm \
	blib/lib/Text/Unidecode/x6d.pm \
	lib/Text/Unidecode/xb9.pm \
	blib/lib/Text/Unidecode/xb9.pm \
	lib/Text/Unidecode/xbf.pm \
	blib/lib/Text/Unidecode/xbf.pm \
	lib/Text/Unidecode/x1e.pm \
	blib/lib/Text/Unidecode/x1e.pm \
	lib/Text/Unidecode/xd6.pm \
	blib/lib/Text/Unidecode/xd6.pm \
	lib/Text/Unidecode/x0a.pm \
	blib/lib/Text/Unidecode/x0a.pm \
	lib/Text/Unidecode/x9a.pm \
	blib/lib/Text/Unidecode/x9a.pm \
	lib/Text/Unidecode/xbd.pm \
	blib/lib/Text/Unidecode/xbd.pm \
	lib/Text/Unidecode/x94.pm \
	blib/lib/Text/Unidecode/x94.pm \
	lib/Text/Unidecode/x5d.pm \
	blib/lib/Text/Unidecode/x5d.pm \
	lib/Text/Unidecode/x74.pm \
	blib/lib/Text/Unidecode/x74.pm \
	lib/Text/Unidecode/x58.pm \
	blib/lib/Text/Unidecode/x58.pm \
	lib/Text/Unidecode/x87.pm \
	blib/lib/Text/Unidecode/x87.pm \
	lib/Text/Unidecode/xcb.pm \
	blib/lib/Text/Unidecode/xcb.pm \
	lib/Text/Unidecode/x6e.pm \
	blib/lib/Text/Unidecode/x6e.pm \
	lib/Text/Unidecode/x93.pm \
	blib/lib/Text/Unidecode/x93.pm \
	lib/Text/Unidecode.pm \
	blib/lib/Text/Unidecode.pm \
	lib/Text/Unidecode/x91.pm \
	blib/lib/Text/Unidecode/x91.pm \
	lib/Text/Unidecode/x13.pm \
	blib/lib/Text/Unidecode/x13.pm \
	lib/Text/Unidecode/xb0.pm \
	blib/lib/Text/Unidecode/xb0.pm \
	lib/Text/Unidecode/x03.pm \
	blib/lib/Text/Unidecode/x03.pm \
	lib/Text/Unidecode/xb2.pm \
	blib/lib/Text/Unidecode/xb2.pm \
	lib/Text/Unidecode/x52.pm \
	blib/lib/Text/Unidecode/x52.pm \
	lib/Text/Unidecode/x25.pm \
	blib/lib/Text/Unidecode/x25.pm \
	lib/Text/Unidecode/x5e.pm \
	blib/lib/Text/Unidecode/x5e.pm \
	lib/Text/Unidecode/x67.pm \
	blib/lib/Text/Unidecode/x67.pm \
	lib/Text/Unidecode/xc8.pm \
	blib/lib/Text/Unidecode/xc8.pm \
	lib/Text/Unidecode/x99.pm \
	blib/lib/Text/Unidecode/x99.pm \
	lib/Text/Unidecode/x00.pm \
	blib/lib/Text/Unidecode/x00.pm \
	lib/Text/Unidecode/x7d.pm \
	blib/lib/Text/Unidecode/x7d.pm \
	lib/Text/Unidecode/x5c.pm \
	blib/lib/Text/Unidecode/x5c.pm \
	lib/Text/Unidecode/xb8.pm \
	blib/lib/Text/Unidecode/xb8.pm \
	lib/Text/Unidecode/x54.pm \
	blib/lib/Text/Unidecode/x54.pm \
	lib/Text/Unidecode/x96.pm \
	blib/lib/Text/Unidecode/x96.pm \
	lib/Text/Unidecode/xba.pm \
	blib/lib/Text/Unidecode/xba.pm \
	lib/Text/Unidecode/xfb.pm \
	blib/lib/Text/Unidecode/xfb.pm \
	lib/Text/Unidecode/x75.pm \
	blib/lib/Text/Unidecode/x75.pm \
	lib/Text/Unidecode/xc3.pm \
	blib/lib/Text/Unidecode/xc3.pm \
	lib/Text/Unidecode/x89.pm \
	blib/lib/Text/Unidecode/x89.pm \
	lib/Text/Unidecode/x95.pm \
	blib/lib/Text/Unidecode/x95.pm \
	lib/Text/Unidecode/x6c.pm \
	blib/lib/Text/Unidecode/x6c.pm \
	lib/Text/Unidecode/x7f.pm \
	blib/lib/Text/Unidecode/x7f.pm \
	lib/Text/Unidecode/xa0.pm \
	blib/lib/Text/Unidecode/xa0.pm \
	lib/Text/Unidecode/x2f.pm \
	blib/lib/Text/Unidecode/x2f.pm \
	lib/Text/Unidecode/x62.pm \
	blib/lib/Text/Unidecode/x62.pm \
	lib/Text/Unidecode/x65.pm \
	blib/lib/Text/Unidecode/x65.pm \
	lib/Text/Unidecode/x57.pm \
	blib/lib/Text/Unidecode/x57.pm \
	lib/Text/Unidecode/x92.pm \
	blib/lib/Text/Unidecode/x92.pm \
	lib/Text/Unidecode/xac.pm \
	blib/lib/Text/Unidecode/xac.pm \
	lib/Text/Unidecode/x80.pm \
	blib/lib/Text/Unidecode/x80.pm \
	lib/Text/Unidecode/x98.pm \
	blib/lib/Text/Unidecode/x98.pm \
	lib/Text/Unidecode/x2e.pm \
	blib/lib/Text/Unidecode/x2e.pm \
	lib/Text/Unidecode/xd1.pm \
	blib/lib/Text/Unidecode/xd1.pm \
	lib/Text/Unidecode/xb3.pm \
	blib/lib/Text/Unidecode/xb3.pm \
	lib/Text/Unidecode/xc4.pm \
	blib/lib/Text/Unidecode/xc4.pm \
	lib/Text/Unidecode/xc0.pm \
	blib/lib/Text/Unidecode/xc0.pm \
	lib/Text/Unidecode/x01.pm \
	blib/lib/Text/Unidecode/x01.pm \
	lib/Text/Unidecode/x53.pm \
	blib/lib/Text/Unidecode/x53.pm \
	lib/Text/Unidecode/xc6.pm \
	blib/lib/Text/Unidecode/xc6.pm \
	lib/Text/Unidecode/xa4.pm \
	blib/lib/Text/Unidecode/xa4.pm \
	lib/Text/Unidecode/x5a.pm \
	blib/lib/Text/Unidecode/x5a.pm \
	lib/Text/Unidecode/x28.pm \
	blib/lib/Text/Unidecode/x28.pm \
	lib/Text/Unidecode/xae.pm \
	blib/lib/Text/Unidecode/xae.pm \
	lib/Text/Unidecode/xa1.pm \
	blib/lib/Text/Unidecode/xa1.pm \
	lib/Text/Unidecode/x56.pm \
	blib/lib/Text/Unidecode/x56.pm \
	lib/Text/Unidecode/x79.pm \
	blib/lib/Text/Unidecode/x79.pm \
	lib/Text/Unidecode/x32.pm \
	blib/lib/Text/Unidecode/x32.pm \
	lib/Text/Unidecode/x8b.pm \
	blib/lib/Text/Unidecode/x8b.pm \
	lib/Text/Unidecode/x8f.pm \
	blib/lib/Text/Unidecode/x8f.pm \
	lib/Text/Unidecode/x76.pm \
	blib/lib/Text/Unidecode/x76.pm \
	lib/Text/Unidecode/x8a.pm \
	blib/lib/Text/Unidecode/x8a.pm \
	lib/Text/Unidecode/xb7.pm \
	blib/lib/Text/Unidecode/xb7.pm \
	lib/Text/Unidecode/x05.pm \
	blib/lib/Text/Unidecode/x05.pm \
	lib/Text/Unidecode/xd4.pm \
	blib/lib/Text/Unidecode/xd4.pm \
	lib/Text/Unidecode/x83.pm \
	blib/lib/Text/Unidecode/x83.pm \
	lib/Text/Unidecode/x0e.pm \
	blib/lib/Text/Unidecode/x0e.pm \
	lib/Text/Unidecode/x86.pm \
	blib/lib/Text/Unidecode/x86.pm \
	lib/Text/Unidecode/xff.pm \
	blib/lib/Text/Unidecode/xff.pm \
	lib/Text/Unidecode/x26.pm \
	blib/lib/Text/Unidecode/x26.pm \
	lib/Text/Unidecode/xbe.pm \
	blib/lib/Text/Unidecode/xbe.pm \
	lib/Text/Unidecode/xc7.pm \
	blib/lib/Text/Unidecode/xc7.pm \
	lib/Text/Unidecode/xfe.pm \
	blib/lib/Text/Unidecode/xfe.pm \
	lib/Text/Unidecode/xc2.pm \
	blib/lib/Text/Unidecode/xc2.pm \
	lib/Text/Unidecode/x1f.pm \
	blib/lib/Text/Unidecode/x1f.pm \
	lib/Text/Unidecode/x8c.pm \
	blib/lib/Text/Unidecode/x8c.pm \
	lib/Text/Unidecode/x21.pm \
	blib/lib/Text/Unidecode/x21.pm \
	lib/Text/Unidecode/xd0.pm \
	blib/lib/Text/Unidecode/xd0.pm \
	lib/Text/Unidecode/x50.pm \
	blib/lib/Text/Unidecode/x50.pm \
	lib/Text/Unidecode/xc1.pm \
	blib/lib/Text/Unidecode/xc1.pm \
	lib/Text/Unidecode/x0c.pm \
	blib/lib/Text/Unidecode/x0c.pm \
	lib/Text/Unidecode/xbc.pm \
	blib/lib/Text/Unidecode/xbc.pm \
	lib/Text/Unidecode/xbb.pm \
	blib/lib/Text/Unidecode/xbb.pm \
	lib/Text/Unidecode/x0d.pm \
	blib/lib/Text/Unidecode/x0d.pm \
	lib/Text/Unidecode/xca.pm \
	blib/lib/Text/Unidecode/xca.pm \
	lib/Text/Unidecode/xcd.pm \
	blib/lib/Text/Unidecode/xcd.pm \
	lib/Text/Unidecode/x24.pm \
	blib/lib/Text/Unidecode/x24.pm \
	lib/Text/Unidecode/xd3.pm \
	blib/lib/Text/Unidecode/xd3.pm \
	lib/Text/Unidecode/x66.pm \
	blib/lib/Text/Unidecode/x66.pm \
	lib/Text/Unidecode/xf9.pm \
	blib/lib/Text/Unidecode/xf9.pm \
	lib/Text/Unidecode/xd7.pm \
	blib/lib/Text/Unidecode/xd7.pm \
	lib/Text/Unidecode/x27.pm \
	blib/lib/Text/Unidecode/x27.pm \
	lib/Text/Unidecode/x14.pm \
	blib/lib/Text/Unidecode/x14.pm \
	lib/Text/Unidecode/x60.pm \
	blib/lib/Text/Unidecode/x60.pm \
	lib/Text/Unidecode/x84.pm \
	blib/lib/Text/Unidecode/x84.pm \
	lib/Text/Unidecode/x71.pm \
	blib/lib/Text/Unidecode/x71.pm \
	lib/Text/Unidecode/x02.pm \
	blib/lib/Text/Unidecode/x02.pm \
	lib/Text/Unidecode/x12.pm \
	blib/lib/Text/Unidecode/x12.pm \
	lib/Text/Unidecode/x20.pm \
	blib/lib/Text/Unidecode/x20.pm \
	lib/Text/Unidecode/x88.pm \
	blib/lib/Text/Unidecode/x88.pm \
	lib/Text/Unidecode/x70.pm \
	blib/lib/Text/Unidecode/x70.pm \
	lib/Text/Unidecode/xcf.pm \
	blib/lib/Text/Unidecode/xcf.pm \
	lib/Text/Unidecode/x6a.pm \
	blib/lib/Text/Unidecode/x6a.pm \
	lib/Text/Unidecode/x7c.pm \
	blib/lib/Text/Unidecode/x7c.pm \
	lib/Text/Unidecode/xfc.pm \
	blib/lib/Text/Unidecode/xfc.pm \
	lib/Text/Unidecode/xad.pm \
	blib/lib/Text/Unidecode/xad.pm \
	lib/Text/Unidecode/x04.pm \
	blib/lib/Text/Unidecode/x04.pm \
	lib/Text/Unidecode/xb4.pm \
	blib/lib/Text/Unidecode/xb4.pm \
	lib/Text/Unidecode/xaf.pm \
	blib/lib/Text/Unidecode/xaf.pm \
	lib/Text/Unidecode/x8d.pm \
	blib/lib/Text/Unidecode/x8d.pm \
	lib/Text/Unidecode/x9d.pm \
	blib/lib/Text/Unidecode/x9d.pm \
	lib/Text/Unidecode/x63.pm \
	blib/lib/Text/Unidecode/x63.pm \
	lib/Text/Unidecode/x10.pm \
	blib/lib/Text/Unidecode/x10.pm \
	lib/Text/Unidecode/x11.pm \
	blib/lib/Text/Unidecode/x11.pm \
	lib/Text/Unidecode/x7a.pm \
	blib/lib/Text/Unidecode/x7a.pm \
	lib/Text/Unidecode/xc5.pm \
	blib/lib/Text/Unidecode/xc5.pm \
	lib/Text/Unidecode/x16.pm \
	blib/lib/Text/Unidecode/x16.pm \
	lib/Text/Unidecode/x77.pm \
	blib/lib/Text/Unidecode/x77.pm \
	lib/Text/Unidecode/x55.pm \
	blib/lib/Text/Unidecode/x55.pm \
	lib/Text/Unidecode/x30.pm \
	blib/lib/Text/Unidecode/x30.pm \
	lib/Text/Unidecode/x9e.pm \
	blib/lib/Text/Unidecode/x9e.pm \
	lib/Text/Unidecode/x15.pm \
	blib/lib/Text/Unidecode/x15.pm \
	lib/Text/Unidecode/x0b.pm \
	blib/lib/Text/Unidecode/x0b.pm \
	lib/Text/Unidecode/x06.pm \
	blib/lib/Text/Unidecode/x06.pm \
	lib/Text/Unidecode/xcc.pm \
	blib/lib/Text/Unidecode/xcc.pm \
	lib/Text/Unidecode/xb5.pm \
	blib/lib/Text/Unidecode/xb5.pm \
	lib/Text/Unidecode/x4e.pm \
	blib/lib/Text/Unidecode/x4e.pm \
	lib/Text/Unidecode/x73.pm \
	blib/lib/Text/Unidecode/x73.pm \
	lib/Text/Unidecode/xb1.pm \
	blib/lib/Text/Unidecode/xb1.pm \
	lib/Text/Unidecode/x61.pm \
	blib/lib/Text/Unidecode/x61.pm \
	lib/Text/Unidecode/x22.pm \
	blib/lib/Text/Unidecode/x22.pm \
	lib/Text/Unidecode/x85.pm \
	blib/lib/Text/Unidecode/x85.pm \
	lib/Text/Unidecode/x23.pm \
	blib/lib/Text/Unidecode/x23.pm \
	lib/Text/Unidecode/x9b.pm \
	blib/lib/Text/Unidecode/x9b.pm \
	lib/Text/Unidecode/x17.pm \
	blib/lib/Text/Unidecode/x17.pm \
	lib/Text/Unidecode/x59.pm \
	blib/lib/Text/Unidecode/x59.pm \
	lib/Text/Unidecode/x69.pm \
	blib/lib/Text/Unidecode/x69.pm \
	lib/Text/Unidecode/x6f.pm \
	blib/lib/Text/Unidecode/x6f.pm \
	lib/Text/Unidecode/x4f.pm \
	blib/lib/Text/Unidecode/x4f.pm \
	lib/Text/Unidecode/x9f.pm \
	blib/lib/Text/Unidecode/x9f.pm \
	lib/Text/Unidecode/x7e.pm \
	blib/lib/Text/Unidecode/x7e.pm \
	lib/Text/Unidecode/x7b.pm \
	blib/lib/Text/Unidecode/x7b.pm \
	lib/Text/Unidecode/x5f.pm \
	blib/lib/Text/Unidecode/x5f.pm \
	lib/Text/Unidecode/xfd.pm \
	blib/lib/Text/Unidecode/xfd.pm \
	lib/Text/Unidecode/x51.pm \
	blib/lib/Text/Unidecode/x51.pm \
	lib/Text/Unidecode/x6b.pm \
	blib/lib/Text/Unidecode/x6b.pm \
	lib/Text/Unidecode/xa3.pm \
	blib/lib/Text/Unidecode/xa3.pm \
	lib/Text/Unidecode/x8e.pm \
	blib/lib/Text/Unidecode/x8e.pm \
	lib/Text/Unidecode/xc9.pm \
	blib/lib/Text/Unidecode/xc9.pm \
	lib/Text/Unidecode/x9c.pm \
	blib/lib/Text/Unidecode/x9c.pm \
	lib/Text/Unidecode/x97.pm \
	blib/lib/Text/Unidecode/x97.pm \
	lib/Text/Unidecode/xd5.pm \
	blib/lib/Text/Unidecode/xd5.pm \
	lib/Text/Unidecode/x0f.pm \
	blib/lib/Text/Unidecode/x0f.pm \
	lib/Text/Unidecode/x64.pm \
	blib/lib/Text/Unidecode/x64.pm \
	lib/Text/Unidecode/x68.pm \
	blib/lib/Text/Unidecode/x68.pm \
	lib/Text/Unidecode/x81.pm \
	blib/lib/Text/Unidecode/x81.pm \
	lib/Text/Unidecode/x72.pm \
	blib/lib/Text/Unidecode/x72.pm \
	lib/Text/Unidecode/x5b.pm \
	blib/lib/Text/Unidecode/x5b.pm \
	lib/Text/Unidecode/x78.pm \
	blib/lib/Text/Unidecode/x78.pm \
	lib/Text/Unidecode/xce.pm \
	blib/lib/Text/Unidecode/xce.pm \
	lib/Text/Unidecode/x09.pm \
	blib/lib/Text/Unidecode/x09.pm \
	lib/Text/Unidecode/xa2.pm \
	blib/lib/Text/Unidecode/xa2.pm \
	lib/Text/Unidecode/x90.pm \
	blib/lib/Text/Unidecode/x90.pm \
	lib/Text/Unidecode/x4d.pm \
	blib/lib/Text/Unidecode/x4d.pm \
	lib/Text/Unidecode/x82.pm \
	blib/lib/Text/Unidecode/x82.pm \
	lib/Text/Unidecode/xb6.pm \
	blib/lib/Text/Unidecode/xb6.pm \
	lib/Text/Unidecode/xfa.pm \
	blib/lib/Text/Unidecode/xfa.pm \
	lib/Text/Unidecode/x18.pm \
	blib/lib/Text/Unidecode/x18.pm \
	lib/Text/Unidecode/x07.pm \
	blib/lib/Text/Unidecode/x07.pm \
	lib/Text/Unidecode/x31.pm \
	blib/lib/Text/Unidecode/x31.pm \
	lib/Text/Unidecode/xd2.pm \
	blib/lib/Text/Unidecode/xd2.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 1.50_01
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)'



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(SHELL) -c true
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) "-MExtUtils::Command" -e mkpath
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) "-MExtUtils::Command" -e eqtime
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install({@ARGV}, '\''$(VERBINST)'\'', 0, '\''$(UNINST)'\'');'
DOC_INSTALL = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e perllocal_install
UNINSTALL = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e uninstall
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e warn_if_old_packlist
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(PERLRUN) "-MExtUtils::MY" -e "MY->fixin(shift)"


# --- MakeMaker makemakerdflt section:
makemakerdflt: all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip -9f
SUFFIX = gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = Text-Unidecode
DISTVNAME = Text-Unidecode-0.04


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) 755 $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) 755 $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) 755 $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) 755 $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) 755 $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) 755 $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) 755 $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) 755 $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	lib/Text/Unidecode.pm \
	lib/Text/Unidecode.pm
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) \
	  lib/Text/Unidecode.pm $(INST_MAN3DIR)/Text::Unidecode.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  $(BASEEXT).x $(BOOTSTRAP) \
	  perl$(EXE_EXT) tmon.out \
	  *$(OBJ_EXT) pm_to_blib \
	  $(INST_ARCHAUTODIR)/extralibs.ld blibdirs.ts \
	  core.[0-9][0-9][0-9][0-9][0-9] *perl.core \
	  core.*perl.*.? $(MAKE_APERL_FILE) \
	  perl $(BASEEXT).def \
	  core.[0-9][0-9][0-9] mon.out \
	  lib$(BASEEXT).def perlmain.c \
	  perl.exe so_locations \
	  $(BASEEXT).exp 
	- $(RM_RF) \
	  blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '# http://module-build.sourceforge.net/META-spec.html' > META_new.yml
	$(NOECHO) $(ECHO) '#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#' >> META_new.yml
	$(NOECHO) $(ECHO) 'name:         Text-Unidecode' >> META_new.yml
	$(NOECHO) $(ECHO) 'version:      0.04' >> META_new.yml
	$(NOECHO) $(ECHO) 'version_from: lib/Text/Unidecode.pm' >> META_new.yml
	$(NOECHO) $(ECHO) 'installdirs:  site' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '' >> META_new.yml
	$(NOECHO) $(ECHO) 'distribution_type: module' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by: ExtUtils::MakeMaker version 6.30_01' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ *.orig */*~ */*.orig



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';'

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"'



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"'
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: all pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: all pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: all pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: all pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install ::
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install ::
	$(NOECHO) umask 02; $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSITESCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install ::
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLVENDORSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install ::

doc_site_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLSITEARCH)/perllocal.pod
	-$(NOECHO) umask 02; $(MKPATH) $(DESTINSTALLSITEARCH)
	-$(NOECHO) umask 02; $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLSITEARCH)/perllocal.pod

doc_vendor_install ::


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::



# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE:
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	false



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /usr/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR= \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = 
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE)

test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd:
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="0,04,0,0">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <TITLE>$(DISTNAME)</TITLE>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT></ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR></AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <OS NAME="$(OSNAME)" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="i486-linux-gnu-thread-multi" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', '\''$(PM_FILTER)'\'')' \
	  lib/Text/Unidecode/x33.pm blib/lib/Text/Unidecode/x33.pm \
	  lib/Text/Unidecode/x6d.pm blib/lib/Text/Unidecode/x6d.pm \
	  lib/Text/Unidecode/xb9.pm blib/lib/Text/Unidecode/xb9.pm \
	  lib/Text/Unidecode/xbf.pm blib/lib/Text/Unidecode/xbf.pm \
	  lib/Text/Unidecode/x1e.pm blib/lib/Text/Unidecode/x1e.pm \
	  lib/Text/Unidecode/xd6.pm blib/lib/Text/Unidecode/xd6.pm \
	  lib/Text/Unidecode/x0a.pm blib/lib/Text/Unidecode/x0a.pm \
	  lib/Text/Unidecode/x9a.pm blib/lib/Text/Unidecode/x9a.pm \
	  lib/Text/Unidecode/xbd.pm blib/lib/Text/Unidecode/xbd.pm \
	  lib/Text/Unidecode/x94.pm blib/lib/Text/Unidecode/x94.pm \
	  lib/Text/Unidecode/x5d.pm blib/lib/Text/Unidecode/x5d.pm \
	  lib/Text/Unidecode/x74.pm blib/lib/Text/Unidecode/x74.pm \
	  lib/Text/Unidecode/x58.pm blib/lib/Text/Unidecode/x58.pm \
	  lib/Text/Unidecode/x87.pm blib/lib/Text/Unidecode/x87.pm \
	  lib/Text/Unidecode/xcb.pm blib/lib/Text/Unidecode/xcb.pm \
	  lib/Text/Unidecode/x6e.pm blib/lib/Text/Unidecode/x6e.pm \
	  lib/Text/Unidecode/x93.pm blib/lib/Text/Unidecode/x93.pm \
	  lib/Text/Unidecode.pm blib/lib/Text/Unidecode.pm \
	  lib/Text/Unidecode/x91.pm blib/lib/Text/Unidecode/x91.pm \
	  lib/Text/Unidecode/x13.pm blib/lib/Text/Unidecode/x13.pm \
	  lib/Text/Unidecode/xb0.pm blib/lib/Text/Unidecode/xb0.pm \
	  lib/Text/Unidecode/x03.pm blib/lib/Text/Unidecode/x03.pm \
	  lib/Text/Unidecode/xb2.pm blib/lib/Text/Unidecode/xb2.pm \
	  lib/Text/Unidecode/x52.pm blib/lib/Text/Unidecode/x52.pm \
	  lib/Text/Unidecode/x25.pm blib/lib/Text/Unidecode/x25.pm \
	  lib/Text/Unidecode/x5e.pm blib/lib/Text/Unidecode/x5e.pm \
	  lib/Text/Unidecode/x67.pm blib/lib/Text/Unidecode/x67.pm \
	  lib/Text/Unidecode/xc8.pm blib/lib/Text/Unidecode/xc8.pm \
	  lib/Text/Unidecode/x99.pm blib/lib/Text/Unidecode/x99.pm \
	  lib/Text/Unidecode/x00.pm blib/lib/Text/Unidecode/x00.pm \
	  lib/Text/Unidecode/x7d.pm blib/lib/Text/Unidecode/x7d.pm \
	  lib/Text/Unidecode/x5c.pm blib/lib/Text/Unidecode/x5c.pm \
	  lib/Text/Unidecode/xb8.pm blib/lib/Text/Unidecode/xb8.pm \
	  lib/Text/Unidecode/x54.pm blib/lib/Text/Unidecode/x54.pm \
	  lib/Text/Unidecode/x96.pm blib/lib/Text/Unidecode/x96.pm \
	  lib/Text/Unidecode/xba.pm blib/lib/Text/Unidecode/xba.pm \
	  lib/Text/Unidecode/xfb.pm blib/lib/Text/Unidecode/xfb.pm \
	  lib/Text/Unidecode/x75.pm blib/lib/Text/Unidecode/x75.pm \
	  lib/Text/Unidecode/xc3.pm blib/lib/Text/Unidecode/xc3.pm \
	  lib/Text/Unidecode/x89.pm blib/lib/Text/Unidecode/x89.pm \
	  lib/Text/Unidecode/x95.pm blib/lib/Text/Unidecode/x95.pm \
	  lib/Text/Unidecode/x6c.pm blib/lib/Text/Unidecode/x6c.pm \
	  lib/Text/Unidecode/x7f.pm blib/lib/Text/Unidecode/x7f.pm \
	  lib/Text/Unidecode/xa0.pm blib/lib/Text/Unidecode/xa0.pm \
	  lib/Text/Unidecode/x2f.pm blib/lib/Text/Unidecode/x2f.pm \
	  lib/Text/Unidecode/x62.pm blib/lib/Text/Unidecode/x62.pm \
	  lib/Text/Unidecode/x65.pm blib/lib/Text/Unidecode/x65.pm \
	  lib/Text/Unidecode/x57.pm blib/lib/Text/Unidecode/x57.pm \
	  lib/Text/Unidecode/x92.pm blib/lib/Text/Unidecode/x92.pm \
	  lib/Text/Unidecode/xac.pm blib/lib/Text/Unidecode/xac.pm \
	  lib/Text/Unidecode/x80.pm blib/lib/Text/Unidecode/x80.pm \
	  lib/Text/Unidecode/x98.pm blib/lib/Text/Unidecode/x98.pm \
	  lib/Text/Unidecode/x2e.pm blib/lib/Text/Unidecode/x2e.pm \
	  lib/Text/Unidecode/xd1.pm blib/lib/Text/Unidecode/xd1.pm \
	  lib/Text/Unidecode/xb3.pm blib/lib/Text/Unidecode/xb3.pm \
	  lib/Text/Unidecode/xc4.pm blib/lib/Text/Unidecode/xc4.pm \
	  lib/Text/Unidecode/xc0.pm blib/lib/Text/Unidecode/xc0.pm \
	  lib/Text/Unidecode/x01.pm blib/lib/Text/Unidecode/x01.pm \
	  lib/Text/Unidecode/x53.pm blib/lib/Text/Unidecode/x53.pm \
	  lib/Text/Unidecode/xc6.pm blib/lib/Text/Unidecode/xc6.pm \
	  lib/Text/Unidecode/xa4.pm blib/lib/Text/Unidecode/xa4.pm \
	  lib/Text/Unidecode/x5a.pm blib/lib/Text/Unidecode/x5a.pm \
	  lib/Text/Unidecode/x28.pm blib/lib/Text/Unidecode/x28.pm \
	  lib/Text/Unidecode/xae.pm blib/lib/Text/Unidecode/xae.pm \
	  lib/Text/Unidecode/xa1.pm blib/lib/Text/Unidecode/xa1.pm \
	  lib/Text/Unidecode/x56.pm blib/lib/Text/Unidecode/x56.pm \
	  lib/Text/Unidecode/x79.pm blib/lib/Text/Unidecode/x79.pm \
	  lib/Text/Unidecode/x32.pm blib/lib/Text/Unidecode/x32.pm \
	  lib/Text/Unidecode/x8b.pm blib/lib/Text/Unidecode/x8b.pm \
	  lib/Text/Unidecode/x8f.pm blib/lib/Text/Unidecode/x8f.pm \
	  lib/Text/Unidecode/x76.pm blib/lib/Text/Unidecode/x76.pm \
	  lib/Text/Unidecode/x8a.pm blib/lib/Text/Unidecode/x8a.pm \
	  lib/Text/Unidecode/xb7.pm blib/lib/Text/Unidecode/xb7.pm \
	  lib/Text/Unidecode/x05.pm blib/lib/Text/Unidecode/x05.pm \
	  lib/Text/Unidecode/xd4.pm blib/lib/Text/Unidecode/xd4.pm \
	  lib/Text/Unidecode/x83.pm blib/lib/Text/Unidecode/x83.pm \
	  lib/Text/Unidecode/x0e.pm blib/lib/Text/Unidecode/x0e.pm \
	  lib/Text/Unidecode/x86.pm blib/lib/Text/Unidecode/x86.pm \
	  lib/Text/Unidecode/xff.pm blib/lib/Text/Unidecode/xff.pm \
	  lib/Text/Unidecode/x26.pm blib/lib/Text/Unidecode/x26.pm \
	  lib/Text/Unidecode/xbe.pm blib/lib/Text/Unidecode/xbe.pm \
	  lib/Text/Unidecode/xc7.pm blib/lib/Text/Unidecode/xc7.pm \
	  lib/Text/Unidecode/xfe.pm blib/lib/Text/Unidecode/xfe.pm \
	  lib/Text/Unidecode/xc2.pm blib/lib/Text/Unidecode/xc2.pm \
	  lib/Text/Unidecode/x1f.pm blib/lib/Text/Unidecode/x1f.pm \
	  lib/Text/Unidecode/x8c.pm blib/lib/Text/Unidecode/x8c.pm \
	  lib/Text/Unidecode/x21.pm blib/lib/Text/Unidecode/x21.pm \
	  lib/Text/Unidecode/xd0.pm blib/lib/Text/Unidecode/xd0.pm \
	  lib/Text/Unidecode/x50.pm blib/lib/Text/Unidecode/x50.pm \
	  lib/Text/Unidecode/xc1.pm blib/lib/Text/Unidecode/xc1.pm \
	  lib/Text/Unidecode/x0c.pm blib/lib/Text/Unidecode/x0c.pm \
	  lib/Text/Unidecode/xbc.pm blib/lib/Text/Unidecode/xbc.pm \
	  lib/Text/Unidecode/xbb.pm blib/lib/Text/Unidecode/xbb.pm \
	  lib/Text/Unidecode/x0d.pm blib/lib/Text/Unidecode/x0d.pm \
	  lib/Text/Unidecode/xca.pm blib/lib/Text/Unidecode/xca.pm \
	  lib/Text/Unidecode/xcd.pm blib/lib/Text/Unidecode/xcd.pm \
	  lib/Text/Unidecode/x24.pm blib/lib/Text/Unidecode/x24.pm \
	  lib/Text/Unidecode/xd3.pm blib/lib/Text/Unidecode/xd3.pm \
	  lib/Text/Unidecode/x66.pm blib/lib/Text/Unidecode/x66.pm \
	  lib/Text/Unidecode/xf9.pm blib/lib/Text/Unidecode/xf9.pm \
	  lib/Text/Unidecode/xd7.pm blib/lib/Text/Unidecode/xd7.pm \
	  lib/Text/Unidecode/x27.pm blib/lib/Text/Unidecode/x27.pm \
	  lib/Text/Unidecode/x14.pm blib/lib/Text/Unidecode/x14.pm \
	  lib/Text/Unidecode/x60.pm blib/lib/Text/Unidecode/x60.pm \
	  lib/Text/Unidecode/x84.pm blib/lib/Text/Unidecode/x84.pm \
	  lib/Text/Unidecode/x71.pm blib/lib/Text/Unidecode/x71.pm \
	  lib/Text/Unidecode/x02.pm blib/lib/Text/Unidecode/x02.pm \
	  lib/Text/Unidecode/x12.pm blib/lib/Text/Unidecode/x12.pm \
	  lib/Text/Unidecode/x20.pm blib/lib/Text/Unidecode/x20.pm \
	  lib/Text/Unidecode/x88.pm blib/lib/Text/Unidecode/x88.pm \
	  lib/Text/Unidecode/x70.pm blib/lib/Text/Unidecode/x70.pm \
	  lib/Text/Unidecode/xcf.pm blib/lib/Text/Unidecode/xcf.pm \
	  lib/Text/Unidecode/x6a.pm blib/lib/Text/Unidecode/x6a.pm \
	  lib/Text/Unidecode/x7c.pm blib/lib/Text/Unidecode/x7c.pm \
	  lib/Text/Unidecode/xfc.pm blib/lib/Text/Unidecode/xfc.pm \
	  lib/Text/Unidecode/xad.pm blib/lib/Text/Unidecode/xad.pm \
	  lib/Text/Unidecode/x04.pm blib/lib/Text/Unidecode/x04.pm \
	  lib/Text/Unidecode/xb4.pm blib/lib/Text/Unidecode/xb4.pm \
	  lib/Text/Unidecode/xaf.pm blib/lib/Text/Unidecode/xaf.pm \
	  lib/Text/Unidecode/x8d.pm blib/lib/Text/Unidecode/x8d.pm \
	  lib/Text/Unidecode/x9d.pm blib/lib/Text/Unidecode/x9d.pm \
	  lib/Text/Unidecode/x63.pm blib/lib/Text/Unidecode/x63.pm \
	  lib/Text/Unidecode/x10.pm blib/lib/Text/Unidecode/x10.pm \
	  lib/Text/Unidecode/x11.pm blib/lib/Text/Unidecode/x11.pm \
	  lib/Text/Unidecode/x7a.pm blib/lib/Text/Unidecode/x7a.pm \
	  lib/Text/Unidecode/xc5.pm blib/lib/Text/Unidecode/xc5.pm \
	  lib/Text/Unidecode/x16.pm blib/lib/Text/Unidecode/x16.pm \
	  lib/Text/Unidecode/x77.pm blib/lib/Text/Unidecode/x77.pm \
	  lib/Text/Unidecode/x55.pm blib/lib/Text/Unidecode/x55.pm \
	  lib/Text/Unidecode/x30.pm blib/lib/Text/Unidecode/x30.pm \
	  lib/Text/Unidecode/x9e.pm blib/lib/Text/Unidecode/x9e.pm \
	  lib/Text/Unidecode/x15.pm blib/lib/Text/Unidecode/x15.pm \
	  lib/Text/Unidecode/x0b.pm blib/lib/Text/Unidecode/x0b.pm \
	  lib/Text/Unidecode/x06.pm blib/lib/Text/Unidecode/x06.pm \
	  lib/Text/Unidecode/xcc.pm blib/lib/Text/Unidecode/xcc.pm \
	  lib/Text/Unidecode/xb5.pm blib/lib/Text/Unidecode/xb5.pm \
	  lib/Text/Unidecode/x4e.pm blib/lib/Text/Unidecode/x4e.pm \
	  lib/Text/Unidecode/x73.pm blib/lib/Text/Unidecode/x73.pm \
	  lib/Text/Unidecode/xb1.pm blib/lib/Text/Unidecode/xb1.pm \
	  lib/Text/Unidecode/x61.pm blib/lib/Text/Unidecode/x61.pm \
	  lib/Text/Unidecode/x22.pm blib/lib/Text/Unidecode/x22.pm \
	  lib/Text/Unidecode/x85.pm blib/lib/Text/Unidecode/x85.pm \
	  lib/Text/Unidecode/x23.pm blib/lib/Text/Unidecode/x23.pm \
	  lib/Text/Unidecode/x9b.pm blib/lib/Text/Unidecode/x9b.pm \
	  lib/Text/Unidecode/x17.pm blib/lib/Text/Unidecode/x17.pm \
	  lib/Text/Unidecode/x59.pm blib/lib/Text/Unidecode/x59.pm \
	  lib/Text/Unidecode/x69.pm blib/lib/Text/Unidecode/x69.pm \
	  lib/Text/Unidecode/x6f.pm blib/lib/Text/Unidecode/x6f.pm \
	  lib/Text/Unidecode/x4f.pm blib/lib/Text/Unidecode/x4f.pm \
	  lib/Text/Unidecode/x9f.pm blib/lib/Text/Unidecode/x9f.pm \
	  lib/Text/Unidecode/x7e.pm blib/lib/Text/Unidecode/x7e.pm \
	  lib/Text/Unidecode/x7b.pm blib/lib/Text/Unidecode/x7b.pm \
	  lib/Text/Unidecode/x5f.pm blib/lib/Text/Unidecode/x5f.pm \
	  lib/Text/Unidecode/xfd.pm blib/lib/Text/Unidecode/xfd.pm \
	  lib/Text/Unidecode/x51.pm blib/lib/Text/Unidecode/x51.pm \
	  lib/Text/Unidecode/x6b.pm blib/lib/Text/Unidecode/x6b.pm \
	  lib/Text/Unidecode/xa3.pm blib/lib/Text/Unidecode/xa3.pm \
	  lib/Text/Unidecode/x8e.pm blib/lib/Text/Unidecode/x8e.pm \
	  lib/Text/Unidecode/xc9.pm blib/lib/Text/Unidecode/xc9.pm \
	  lib/Text/Unidecode/x9c.pm blib/lib/Text/Unidecode/x9c.pm \
	  lib/Text/Unidecode/x97.pm blib/lib/Text/Unidecode/x97.pm \
	  lib/Text/Unidecode/xd5.pm blib/lib/Text/Unidecode/xd5.pm \
	  lib/Text/Unidecode/x0f.pm blib/lib/Text/Unidecode/x0f.pm \
	  lib/Text/Unidecode/x64.pm blib/lib/Text/Unidecode/x64.pm \
	  lib/Text/Unidecode/x68.pm blib/lib/Text/Unidecode/x68.pm \
	  lib/Text/Unidecode/x81.pm blib/lib/Text/Unidecode/x81.pm \
	  lib/Text/Unidecode/x72.pm blib/lib/Text/Unidecode/x72.pm \
	  lib/Text/Unidecode/x5b.pm blib/lib/Text/Unidecode/x5b.pm \
	  lib/Text/Unidecode/x78.pm blib/lib/Text/Unidecode/x78.pm \
	  lib/Text/Unidecode/xce.pm blib/lib/Text/Unidecode/xce.pm \
	  lib/Text/Unidecode/x09.pm blib/lib/Text/Unidecode/x09.pm \
	  lib/Text/Unidecode/xa2.pm blib/lib/Text/Unidecode/xa2.pm \
	  lib/Text/Unidecode/x90.pm blib/lib/Text/Unidecode/x90.pm \
	  lib/Text/Unidecode/x4d.pm blib/lib/Text/Unidecode/x4d.pm \
	  lib/Text/Unidecode/x82.pm blib/lib/Text/Unidecode/x82.pm \
	  lib/Text/Unidecode/xb6.pm blib/lib/Text/Unidecode/xb6.pm \
	  lib/Text/Unidecode/xfa.pm blib/lib/Text/Unidecode/xfa.pm \
	  lib/Text/Unidecode/x18.pm blib/lib/Text/Unidecode/x18.pm \
	  lib/Text/Unidecode/x07.pm blib/lib/Text/Unidecode/x07.pm \
	  lib/Text/Unidecode/x31.pm blib/lib/Text/Unidecode/x31.pm \
	  lib/Text/Unidecode/xd2.pm blib/lib/Text/Unidecode/xd2.pm 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:


# End.
